### Get users
GET http://localhost:3000/users 

### Get user by id
GET http://localhost:3000/users/9

### Get user profile 
GET http://localhost:3000/users/5f413f05d068dda6b5ee51fa/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjQxM2YwNWQwNjhkZGE2YjVlZTUxZmEiLCJpZCI6OCwiZW1haWwiOiJsdWZmeUBzYWlrb3UuY29tIiwiaWF0IjoxNTk4MTEyMjYwLCJleHAiOjE1OTgzNzE0NjB9.GQ9l-9LelsgZUstgapUJJgy_CZayatBxT7FXye9Df0g


### Register new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "luffy@saikou.com",
    "password": "saikoucreator"
}


### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "luffy@saikou.com",
    "password": "saikoucreator"
}


### Logout
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJkZmMwODBlNTdhYzVmOTM0NTMzYzUiLCJpZCI6MSwiZW1haWwiOiJsZWxvdWNoQG1hcnp1a2kuY29tIiwiaWF0IjoxNTk2ODQ5MjExLCJleHAiOjE1OTcxMDg0MTF9.9dXwPAhG87W3XZ8wXbUIgJEFVyvcTU-MrtNHiFZwuTM


### Set Favorite Anime / Manga
PUT http://localhost:3000/users/5f41cda14c1f722f9ba7b8cd/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjQxY2RhMTRjMWY3MjJmOWJhN2I4Y2QiLCJpZCI6OSwiZW1haWwiOiJsdWZmeUBzYWlrb3UuY29tIiwiaWF0IjoxNTk4MTQ4MDAzLCJleHAiOjE1OTg0MDcyMDN9.FuUyJhyPLFCpJQsDY34P_vyOgIiqLCsCvPQHV2SyKfE
Content-Type: application/json

{
    "favoriteManga": []
}