### Get users
GET http://localhost:3000/users 



### Register new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "lelouch@marzuki.com",
    "password": "saikoucreator"
}


### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "lelouch@marzuki.com",
    "password": "saikoucreator"
}


### Logout
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJkZmMwODBlNTdhYzVmOTM0NTMzYzUiLCJpZCI6MSwiZW1haWwiOiJsZWxvdWNoQG1hcnp1a2kuY29tIiwiaWF0IjoxNTk2ODQ5MjExLCJleHAiOjE1OTcxMDg0MTF9.9dXwPAhG87W3XZ8wXbUIgJEFVyvcTU-MrtNHiFZwuTM

